# Generated by Django 5.1.4 on 2025-04-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manage', '0002_user_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=200)),
                ('reaedr_name', models.CharField(max_length=200)),
                ('reader_contact', models.CharField(max_length=200)),
                ('reader_address', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
